// What group has the highest status in the community? What must people do to gain inclusion in this group?
// In a world where the elite do things
// While trying to do x to become part of group y, person discovers...
