module.exports = {
  enemies: [
    'aliens',
    'clones',
    'zombies',
    'poltergeists',
    'goblins',
    'demi-gods',
    'angry gods',
    'demons',
    'ghouls',
    'mutants',
    'robots',
    'ghosts',
    'werewolves',
    'vampires',
    'mummies',
    'robots',
    'serial killers',
    'androids',
    'wights'
  ],
  creatures: [
    'werewolf',
    'vampire',
    'demi-god',
    'ghost',
    'robot',
    'clone',
    'goblin',
    'serial killer'
  ],
  antagonists: [
    'the Overlord',
    'the King of Monsters',
    'the Grim Reaper',
    'a time traveler',
    'the evil Queen',
    'the Principal',
    'the evil Scientist',
    'the "Gentle" Giant',
    'the Patriarch',
    'Blackbeard',
    'Dracula',
    'the mad Wizard',
    'the evil Witch',
    'The Old One',
    'the tyrannical King',
    'Long John Silver',
    'Bartelby, the Scrivener'
  ],
  npcs: [
    'the Prince',
    'the Princess',
    'the King',
    'the Queen',
    'a unicorn',
    'a griffin',
    'a boy from another world',
    'a girl from another world',
    'a boy from another time',
    'a girl from another time'
  ]
};
