module.exports = [
  'alchemist',
  'writer',
  'clock maker',
  'necromancer',
  'pirate',
  'rogue',
  'magician',
  'mechanic',
  'knight',
  'samurai',
  'ninja',
  'swordsman',
  'monster rancher',
  'blacksmith',
  'sailor',
  'aeronaut',
  'bounty hunter',
  'bandit',
  'jewelcrafter',
  'thief',
  'mercenary',
  'minstrel',
  'scrivener',
  'stage magician',
  'fortune-teller',
  'beast master',
  'summoner',
  'pyromancer'
];
